name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: DockerHub Login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t cicd-pipeline2 .
    - name: Tag the Docker image
      run: docker tag cicd-pipeline2 var/cicd-pipeline2:latest
    - name: Push to Dockerhub
      run: docker push var/cicd-pipeline2:latest
